import type { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from '@/components/AuthProvider';
import { Sidebar } from '@/components/Sidebar/Sidebar';
import { cn } from '@/lib/utils';
import { Profile } from '@/components/Profile/Profile';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className={cn(
            'fixed left-16 top-0 z-50 flex h-full flex-col items-center',
            'py-16',
          )}
        >
          <Sidebar className="flex-1" />
          <AuthProvider>
            <Profile />
          </AuthProvider>
        </div>
        {children}
      </body>
    </html>
  );
}
